// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChh_r4XrFd-dEHvfZT5r3gRzb-1L5O4tY',
    appId: '1:885449612392:web:7159287c5c39d574da6fdd',
    messagingSenderId: '885449612392',
    projectId: 'get-stonkd',
    authDomain: 'get-stonkd.firebaseapp.com',
    storageBucket: 'get-stonkd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZk4YRQkIkQQnUy0h_-5NqHYSamrVHAbM',
    appId: '1:885449612392:android:291bf3505ffc9da7da6fdd',
    messagingSenderId: '885449612392',
    projectId: 'get-stonkd',
    storageBucket: 'get-stonkd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwXNr-CL_gg_V_ii_wG0L_BaR6DAatrDM',
    appId: '1:885449612392:ios:5dfb1ec57483f69eda6fdd',
    messagingSenderId: '885449612392',
    projectId: 'get-stonkd',
    storageBucket: 'get-stonkd.appspot.com',
    iosBundleId: 'com.example.getStonkd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwXNr-CL_gg_V_ii_wG0L_BaR6DAatrDM',
    appId: '1:885449612392:ios:5dfb1ec57483f69eda6fdd',
    messagingSenderId: '885449612392',
    projectId: 'get-stonkd',
    storageBucket: 'get-stonkd.appspot.com',
    iosBundleId: 'com.example.getStonkd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChh_r4XrFd-dEHvfZT5r3gRzb-1L5O4tY',
    appId: '1:885449612392:web:64e8eaff2d646f69da6fdd',
    messagingSenderId: '885449612392',
    projectId: 'get-stonkd',
    authDomain: 'get-stonkd.firebaseapp.com',
    storageBucket: 'get-stonkd.appspot.com',
  );

}